[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.worker.min.js"
  [headers.values]
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.worker.min.mjs"
  [headers.values]
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=86400" 